# Generated by Django 4.0.5 on 2022-06-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_notes_deleted_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='motes_show',
            new_name='notes_show',
        ),
    ]
