# Generated by Django 4.0.5 on 2022-06-16 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_rename_motes_show_notes_notes_show'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-created_date']},
        ),
    ]
